#============== MIH Network ====================================================================
networks:
  mih-network:
    driver: bridge
#============== MIH Containers ====================================================================
services:
  #============== Nginx Proxy Manager ====================================================================
  mih-nginx:
    container_name: mih-nginx
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP
      - "443:443" # Public HTTPS
      - "127.0.0.1:81:81" # Admin Web Port
    volumes:
      - ./mih_nginx/data:/data
      - ./mih_nginx/letsencrypt:/etc/letsencrypt
    networks:
      - mih-network
  #============== FORGEJO ====================================================================
  mih-forgejo:
    image: codeberg.org/forgejo/forgejo:11
    container_name: mih-forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Africa/Johannesburg
      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=mih-forgejo-db:3306
      - FORGEJO__database__NAME=${FORGEJO_SQL_DB}
      - FORGEJO__database__USER=${FORGEJO_SQL_USER}
      - FORGEJO__database__PASSWD=${FORGEJO_SQL_PW}
    restart: always
    networks:
      - mih-network
    volumes:
      - ./mih_git/forgejo:/data
    ports:
      - "127.0.0.1:3000:3000"
      - "222:22"
    depends_on:
      mih-forgejo-db:
        condition: service_healthy
  mih-forgejo-db:
    image: mysql:8.0
    container_name: mih-forgejo-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${FORGEJO_SQL_ROOT_PW}
      - MYSQL_USER=${FORGEJO_SQL_USER}
      - MYSQL_PASSWORD=${FORGEJO_SQL_PW}
      - MYSQL_DATABASE=${FORGEJO_SQL_DB}
    networks:
      - mih-network
    volumes:
      - ./mih_git/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  #============== Super Token Auth ====================================================================
  mih-supertokens:
    container_name: mih-supertokens
    image: supertokens/supertokens-mysql:latest
    depends_on:
      - mih-db
    ports:
      - "127.0.0.1:3567:3567"
    environment:
      REFRESH_TOKEN_VALIDITY: "604800"
      ACCESS_TOKEN_VALIDITY: "86400"
      PASSWORD_RESET_TOKEN_LIFETIME: "7200000"
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PW}
      MYSQL_HOST: mih-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE_NAME: ${SUPERTOKENS_DB}
      API_KEYS: ${SUPERTOKENS_API_KEY}
    networks:
      - mih-network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
  #============== MIH WordPress ====================================================================
  mih-wordpress:
    container_name: mih-wordpress
    image: wordpress
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    environment:
      WORDPRESS_DB_HOST: mih-wp-db
      WORDPRESS_DB_USER: ${WP_SQL_USER}
      WORDPRESS_DB_PASSWORD: ${WP_SQL_USER_PW}
      WORDPRESS_DB_NAME: ${WP_SQL_DB}
    volumes:
      - ./mih_wp/ui:/var/www/html
    networks:
      - mih-network
  mih-wp-db:
    container_name: mih-wp-db
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_DATABASE: ${WP_SQL_DB}
      MARIADB_USER: ${WP_SQL_USER}
      MARIADB_PASSWORD: ${WP_SQL_USER_PW}
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./mih_wp/database:/var/lib/mysql
    networks:
      - mih-network
  #============== MIH-UX Flutter ====================================================================
  mih-ux:
    container_name: mih-ux
    build:
      context: ./mih_ui
    ports:
      - "127.0.0.1:83:83"
    networks:
      - mih-network
    depends_on:
      - mih-api-hub
  #============== API Hub ====================================================================
  mih-api-hub:
    platform: linux/amd64
    build:
      context: ./mih_api_hub
      target: builder
    container_name: mih-api-hub
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./mih_api_hub:/app
    networks:
      - mih-network
    depends_on:
      - mih-db
  #============== My SQL DB ====================================================================
  mih-db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mih-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PW}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PW}
      MYSQL_DATABASE: ${SUPERTOKENS_DB}
    networks:
      - mih-network
    # ports:
    #   - "127.0.0.1:3306:3306"
    volumes:
      - ./mih_db:/var/lib/mysql
  #============== Adminer ====================================================================
  mih-adminer:
    image: adminer:latest
    container_name: mih-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mih-db
    ports:
      - "127.0.0.1:8082:8080"
    networks:
      - mih-network
    depends_on:
      - mih-db
  #============== Minio File Storage ====================================================================
  mih-minio:
    platform: linux/amd64
    container_name: mih-minio
    hostname: mih-minio
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - "./mih_minio:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PW}
    networks:
      - mih-network
    command: ["server", "/data", "--console-address", ":9001"]
  #============== MIH-Monitor Portainer ====================================================================
  mih-monitor:
    container_name: mih-monitor
    image: portainer/portainer-ce:lts
    ports:
      - "127.0.0.1:9444:9443"
    volumes:
      - ./mih_monitor/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - mih-network
  #============== MIH-AI Ollama ====================================================================
  mih-ai:
    container_name: mih-ai
    image: ollama/ollama:0.30.6
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./mih_ai/ollama/ollama:/root/.ollama
      - ./mih_ai/Modelfile:/root/.ollama/Modelfile
      - ./mih_ai/init-ollama.sh:/root/init-ollama.sh
    entrypoint: ["/bin/bash", "/root/init-ollama.sh"]
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - mih-network
    # === Added section for NVIDIA GPU acceleration ===
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # or specify a number of GPUs
              capabilities: [gpu]
  #============== MIH-Legal ====================================================================
  mih-legal:
    image: nginx:alpine
    container_name: mih-legal
    restart: always
    volumes:
      - ./mih_legal:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:8085:80"
    networks:
      - mih-network
  #============== MIH-Flatpak Repository =========================================================
  mih-flatpak:
    image: nginx:alpine
    container_name: mih-flatpak
    restart: always
    volumes:
      - ./mih_ui/flatpak/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mih_ui/repo:/usr/share/nginx/html:ro
      - ./mih_ui/flatpak/favicon.png:/usr/share/nginx/html/favicon.png:ro
      - ./mih_ui/flatpak/mih-fphub.flatpakrepo:/usr/share/nginx/html/mih-fphub.flatpakrepo:ro
    ports:
      - "127.0.0.1:8086:80"
    networks:
      - mih-network
#============== Firebaase ====================================================================
# firebase:
#   container_name: MIH-firebase-emulator
#   build:
#     context: ./Firebase-emulator
#   environment:
#     DATA_DIRECTORY: "firebase/data"
#     FIREBASE_PROJECT: "mzansi-innovation-hub"
#   ports:
#     - 8082:8080 # FIRESTORE_PORT
#     - 5005:5005 # FIRESTORE_WS_PORT
#     - 4000:4000 # UI_PORT
#     - 9099:9099 # AUTH_PORT
#     - 5000:6001 # Hosting
#   volumes:
#     - ./Firebase-emulator:/srv/firebase:rw
#     # - ./cache:/root/.cache/:rw
#     # - ~/.config/:/root/.config
#     - ./Firebase-emulator/firebase/data:/srv/firebase/data:rw
