#!/bin/sh
# Generated by flutpak — https://github.com/o-murphy/flutpak
APP=/app/mih
if [ "$FLATPAK_ARCH" = "aarch64" ]; then
    ARCH_TRIPLET="aarch64-linux-gnu"
else
    ARCH_TRIPLET="x86_64-linux-gnu"
fi
export __EGL_VENDOR_LIBRARY_FILENAMES="/usr/lib/${ARCH_TRIPLET}/GL/glvnd/egl_vendor.d/50_mesa.json"
export LD_LIBRARY_PATH="$APP/lib:${LD_LIBRARY_PATH:-}"
exec "$APP/mzansi_innovation_hub" "$@"
