// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mzansi_innovation_hub/mih_hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(AppointmentAdapter());
    registerAdapter(BookmarkedBusinessAdapter());
    registerAdapter(BusinessAdapter());
    registerAdapter(BusinessEmployeeAdapter());
    registerAdapter(BusinessUserAdapter());
    registerAdapter(MIHLoyaltyCardAdapter());
    registerAdapter(ProfileLinkAdapter());
    registerAdapter(UserConsentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(AppointmentAdapter());
    registerAdapter(BookmarkedBusinessAdapter());
    registerAdapter(BusinessAdapter());
    registerAdapter(BusinessEmployeeAdapter());
    registerAdapter(BusinessUserAdapter());
    registerAdapter(MIHLoyaltyCardAdapter());
    registerAdapter(ProfileLinkAdapter());
    registerAdapter(UserConsentAdapter());
  }
}
