// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for linux - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-f4sJ4n_fyvrLR193_IIkTsccRVUQxw',
    appId: '1:33677883408:web:47b8021df7fcacd2223295',
    messagingSenderId: '33677883408',
    projectId: 'mzansi-innovation-hub',
    authDomain: 'mzansi-innovation-hub.firebaseapp.com',
    storageBucket: 'mzansi-innovation-hub.firebasestorage.app',
    measurementId: 'G-Y3B5E3HCJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUkjWdu9YcgiF-e9TC5hoiEoCjPyjA5hU',
    appId: '1:33677883408:android:ebd8565991c56257223295',
    messagingSenderId: '33677883408',
    projectId: 'mzansi-innovation-hub',
    storageBucket: 'mzansi-innovation-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqY5I5CXjEtWkUX1YUfKT8IUlln9PUuY',
    appId: '1:33677883408:ios:2048dac086428716223295',
    messagingSenderId: '33677883408',
    projectId: 'mzansi-innovation-hub',
    storageBucket: 'mzansi-innovation-hub.firebasestorage.app',
    iosBundleId: 'za.co.mzansiinnovationhub.mih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqY5I5CXjEtWkUX1YUfKT8IUlln9PUuY',
    appId: '1:33677883408:ios:e2db11a42fc3452e223295',
    messagingSenderId: '33677883408',
    projectId: 'mzansi-innovation-hub',
    storageBucket: 'mzansi-innovation-hub.firebasestorage.app',
    iosBundleId: 'com.example.patientManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-f4sJ4n_fyvrLR193_IIkTsccRVUQxw',
    appId: '1:33677883408:web:e08becaef3261c59223295',
    messagingSenderId: '33677883408',
    projectId: 'mzansi-innovation-hub',
    authDomain: 'mzansi-innovation-hub.firebaseapp.com',
    storageBucket: 'mzansi-innovation-hub.firebasestorage.app',
    measurementId: 'G-FKKENBX8TT',
  );
}
